# ===== Default profile (PostgreSQL) =====
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fintrack
    username: postgres         # <-- change if needed
    password: htetlinaung         # <-- change if needed
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update         # For dev; prefer Flyway/Liquibase in prod
    properties:
      hibernate.format_sql: true
      hibernate.jdbc.time_zone: UTC
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    time-zone: UTC

logging:
  level:
    org.springframework.web: info
    org.hibernate.SQL: warn

# ===== Dev profile (H2 in-memory) =====
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:mem:fintrack;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    org.hibernate.SQL: debug
